// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WEB']!,
    appId: dotenv.env['FIREBASE_WEB_APP_ID']!,
    messagingSenderId: '120450956131',
    projectId: dotenv.env['FIREBASE_PROJECT_ID']!,
    authDomain: 'mindsync-3e85c.firebaseapp.com',
    storageBucket: 'mindsync-3e85c.firebasestorage.app',
    measurementId: 'G-F0XT3NBM7Z',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID']!,
    appId: dotenv.env['FIREBASE_ANDROID_APP_ID']!,
    messagingSenderId: '120450956131',
    projectId: dotenv.env['FIREBASE_PROJECT_ID']!,
    storageBucket: 'mindsync-3e85c.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS']!,
    appId: dotenv.env['FIREBASE_IOS_APP_ID']!,
    messagingSenderId: '120450956131',
    projectId: dotenv.env['FIREBASE_PROJECT_ID']!,
    storageBucket: 'mindsync-3e85c.firebasestorage.app',
    iosBundleId: 'com.example.mindsync',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_MACOS']!,
    appId: dotenv.env['FIREBASE_MACOS_APP_ID']!,
    messagingSenderId: '120450956131',
    projectId: dotenv.env['FIREBASE_PROJECT_ID']!,
    storageBucket: 'mindsync-3e85c.firebasestorage.app',
    iosBundleId: 'com.example.mindsync',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WINDOWS']!,
    appId: dotenv.env['FIREBASE_WINDOWS_APP_ID']!,
    messagingSenderId: '120450956131',
    projectId: dotenv.env['FIREBASE_PROJECT_ID']!,
    authDomain: 'mindsync-3e85c.firebaseapp.com',
    storageBucket: 'mindsync-3e85c.firebasestorage.app',
    measurementId: 'G-1R402Z424M',
  );
}
